# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-chromium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run zip

      - run: ls .output/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-chromium
          path: .output/*-chrome.zip
          include-hidden-files: true
          if-no-files-found: error

  build-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run zip:firefox

      - run: ls .output/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-firefox
          path: .output/firefox-mv3/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zip-firefox
          path: |
            .output/*-firefox.zip
            .output/*-sources.zip
          include-hidden-files: true
          if-no-files-found: error

  sign-amo:
    needs: [ build-firefox ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: zip-firefox
          path: .output/

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Sign
        run: |
          pnpm exec web-ext sign \
            --source-dir .output/firefox-mv3/
            --upload-source-code .output/*-sources.zip
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
          WEB_EXT_CHANNEL: unlisted

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: signed-firefox
          path: web-ext-artifacts/

  # chrome-upload:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: wdzeng/chrome-extension@v1
  #     with:
  #       extension-id: your-extension-id
  #       zip-path: your-extension.zip
  #       client-id: ${{ secrets.CHROME_CLIENT_ID }}
  #       client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
  #       refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  release-upload:
    if: always()
    needs: [ sign-amo, build-chromium ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p uploads/

      - uses: actions/download-artifact@v4
        with:
          name: build-chromium
          path: uploads/

      - uses: actions/download-artifact@v4
        with:
          name: signed-firefox
          path: uploads
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          files: uploads/**
